models:
  llm:
    name: "llama3.1:8b"
    base_url: "http://localhost:11434"
  embeddings:
    name: "recobo/agri-sentence-transformer"
    # Note: No base_url needed for Hugging Face models

vector_db:
  persist_directory: "./data/vector_db"
  collection_name: "plant_pathology"

document_processing:
  chunk_size: 1500
  chunk_overlap: 300
  
chat:
  max_history: 10
  temperature: 0.7
  max_tokens: 2048
  enable_query_rewriting: true  # Enable conversational query rewriting for better context

paths:
  pdf_file: "./data/raw/Plant Pathology_Fifth Edition.pdf"
  processed_data: "./data/processed"
